# Generated by Django 5.2 on 2025-04-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('ST', 'Started'), ('RU', 'Running'), ('CO', 'Completed'), ('FA', 'Failed')], default='CR', max_length=2),
        ),
    ]
